# Generated by Django 5.0.1 on 2024-02-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_id", models.CharField(max_length=20, unique=True)),
                ("published_at", models.DateTimeField()),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("thumbnail_url", models.TextField()),
            ],
        ),
    ]
