# Generated by Django 5.0.1 on 2024-02-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["published_at"], name="videos_vide_publish_dd5f2e_idx"
            ),
        ),
    ]
