# Generated by Django 5.0.1 on 2024-02-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0002_video_videos_vide_publish_dd5f2e_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="video",
            index=models.Index(fields=["id"], name="videos_vide_id_16d88b_idx"),
        ),
    ]
